---
- hosts: local
  become: yes
  tasks:
    - name: Install dependencies on local system
      apt:
        name:
          - p7zip-full
          - xorriso
          - gpg
          - curl
          - net-tools