---
- name: Configure the target system and install dependencies
  become: yes
  apt:
    pkg:
    - p7zip-full
    - xorriso
    - curl
    - wget
    - net-tools

- name: Configure and install non-apt packages
  become: yes
  shell:
    cmd: "python3 -m pip install --upgrade pip && pip3 install --upgrade psutil"

- name: Update apt packages
  become: yes
  apt:
    state: latest
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes