---
- name: Install dependencies
  become: yes
  package:
    name:
      - p7zip-full
      - xorriso
      - gpg
      - curl
      - netstat
    state: present
  with_items:
    - p7zip-full
    - xorriso
    - gpg
    - curl
    - netstat
  when: ansible_os_family != "Darwin"
