---
- name: Configure the target system and install dependencies
  become: yes
  apt:
    pkg:
    - p7zip-full
    - xorriso
    - gpg
    - curl
    - net-tools

- name: Configure and install non-apt packages
  become: yes
  shell:
    cmd: "python3 -m pip install --upgrade pip && pip3 install --upgrade psutil"