---
- name: Configure the target system and install dependencies
  become: yes
  package:
    name:
      - xorriso
      - curl
      - isolinux
    state: present

- name: Create the temporary directory
  file:
    path: "{{ target_dir }}"
    state: directory