---  
- name: Create the target directory
  file:
    path: "{{ target_dir }}"
    state: directory

- name: Download the SHA256 sums
  get_url:
    url: "https://cdimage.debian.org/debian-cd/current/{{ iso_arch }}/iso-cd/SHA256SUMS"
    dest: "{{ target_dir }}"

- name: Get the SHA256 sum for the {{ iso_arch }} ISO
  shell:
    cmd: "grep -m1 \"\" {{ target_dir }}/SHA256SUMS | cut -d ' ' -f1"
  register: sha256sum

- name: Download the latest Debian netinst {{ iso_arch }} server ISO
  get_url:
    url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.2.0-amd64-netinst.iso"
    dest: "{{ target_dir }}/debian-server-{{ iso_arch }}.iso"
    checksum: "sha256:{{ sha256sum.stdout }}"